services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    # env_file:
    #   - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
    command: make dev
  
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app 

