version: '5.1.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    # Режим разработки, без него код 502
    env_file:
      - .env
    command: make dev
  
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app 

