name: CI/CD

on:
  push:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    # Шаги
    steps:
        # 1 шаг - скачивание кода
      - name: Checkout code
        uses: actions/checkout@v5

        # Запуск тестов
      - name: Run tests via Make CI
        run: make ci

        # Авторизация на докер хаб используя пароли из secrets репозитория
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # Сборка и пуш продакшн образа
      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-for-developers-project-74:latest